#!/bin/bash -eux
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generate lock circuit and testbench with passed parameters
cd $DUT/hdl_generator/locksmith
cargo build
cargo run -- \
  --states $NUM_LOCK_STATES \
  --width $LOCK_COMP_WIDTH >$DUT/hdl/$TOPLEVEL.sv
cd $DUT/hdl_generator
python3 generate_lock_tb.py lock_tb_template.sv >$DUT/hdl/${TOPLEVEL}_tb.sv
exit 0
