[package]
name = "locksmith"
version = "0.1.0"
authors = ["Garret Kelly <gdk@google.com>",
"Timothy Trippel <ttrippel@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
kaze = "0.1.9"
rand = "0.7"
structopt = "0.3"
