#!/bin/bash
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LINE_SEP="-------------------------------------------------------------------"

function check_exit_code {
  if [[ "$?" != "0" ]]; then
    exit 1
  fi
}

################################################################################
################################################################################
## Make directory to store simulation output
################################################################################
################################################################################
if [ ! -d "out" ]; then
  mkdir -p out
fi

################################################################################
################################################################################
## Build/Simulated the CORE
################################################################################
################################################################################
make OPT_SLOW=$OPT_SLOW OPT_FAST=$OPT_FAST OPT_GLOBAL=$OPT_GLOBAL cocotb
check_exit_code

################################################################################
################################################################################
## Copy simulation results to out directory
################################################################################
################################################################################
cp tb/cocotb/results.xml out/
cp tb/cocotb/coverage.dat out/
find out -type f -exec chmod 644 {} \;

################################################################################
################################################################################
## Done
################################################################################
################################################################################
echo -e "\e[1;32mSIMULATION SUCCESSFUL -- Done!\e[0m"
exit 0
