#!/bin/bash -eu
# Copyright 2020 Timothy Trippel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Tracing LINE COVERAGE with kcov ..."
rm -rf bin build model *.vcd
CPPFLAGS="-g" DISABLE_VCD_TRACING=1 make -j 4

# Create output dirs
KCOV_ROOT_DIR=logs/kcov
KCOV_TEMP_MERGE_DIR=logs/kcov/temp_merged
rm -rf $KCOV_ROOT_DIR
mkdir -p $KCOV_ROOT_DIR
chmod 777 $KCOV_ROOT_DIR
mkdir -p $KCOV_TEMP_MERGE_DIR

# Trace coverage of each test case
TEST_CASE_NUM=0
# TODO(ttrippel): make sure we are processing seed files in the order they were
# created. Right now we are relying on the alphabetical ordering of the seed
# file names which all start with a unique ID number for AFL.
for TEST_CASE in $(ls -1d out/*/queue/*); do
  echo -n "    Tracing test: $TEST_CASE ... "
  # make output dir
  TEST_CASE_COV_DIR=$KCOV_ROOT_DIR/test_case_$TEST_CASE_NUM
  mkdir -p $TEST_CASE_COV_DIR
  # run kcov
  /src/kcov/build/src/kcov $TEST_CASE_COV_DIR bin/$TOPLEVEL <$TEST_CASE \
    >/dev/null
  echo "Done."

  echo -n "    Merging $TEST_CASE_NUM coverage traces ... "
  # clear out contents of temp merged coverage data dir
  rm -rf $KCOV_TEMP_MERGE_DIR/*
  # merge all existing coverage traces
  /src/kcov/build/src/kcov --merge $KCOV_TEMP_MERGE_DIR \
    $KCOV_ROOT_DIR/test_case_*
  # move out the JSON results (this is what we will save for plotting)
  mv $KCOV_TEMP_MERGE_DIR/kcov-merged/coverage.json \
    $KCOV_ROOT_DIR/cumulative_coverage_${TEST_CASE_NUM}.json
  chmod 666 $KCOV_ROOT_DIR/cumulative_coverage_${TEST_CASE_NUM}.json
  echo "Done."

  # increment test number and update previous output dir
  TEST_CASE_NUM=$((TEST_CASE_NUM + 1))
done
rm -rf $KCOV_TEMP_MERGE_DIR
echo "Done."

# Move all individual test coverage traces out of parent dir and delete
# parent dir as this data is useless (mostly HTML files for viewing web UX).
NUM_TEST_CASES=$((TEST_CASE_NUM - 1))
for IND in $(seq 0 $NUM_TEST_CASES); do
  mv $KCOV_ROOT_DIR/test_case_$IND/$TOPLEVEL.*/coverage.json \
    $KCOV_ROOT_DIR/coverage_$IND.json
  chmod 666 $KCOV_ROOT_DIR/coverage_$IND.json
  rm -rf $KCOV_ROOT_DIR/test_case_$IND
done
echo "Traced LINE COVERAGE from $TEST_CASE_NUM test cases."
