#!/bin/bash -eu
# Copyright 2020 Timothy Trippel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get GCP project details
source get_gcp_config.sh

# Save fuzzing data to GCS
BUCKET_NAME="${PROJECT_ID}-fuzzing-data"
GCS_API_URL="https://storage.googleapis.com/upload/storage/v1/b"
find out -type f -exec curl -X POST --data-binary @{} \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: text" \
  "$GCS_API_URL/$BUCKET_NAME/o?uploadType=media&name=$INSTANCE_NAME/{}" \; >/dev/null
find logs -type f -exec curl -X POST --data-binary @{} \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: text" \
  "$GCS_API_URL/$BUCKET_NAME/o?uploadType=media&name=$INSTANCE_NAME/{}" \; >/dev/null
exit 0
