#!/bin/bash -eux
# Copyright 2021 Timothy Trippel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate HDL from FIRRTL
make -C $DUT_HDL_DIR FIR=${TOPLEVEL}.fir DUT=$TOPLEVEL bin
mkdir -p $DUT/hdl
cp $DUT_HDL_DIR/build/$TOPLEVEL.v hdl/$TOPLEVEL.v
cp $DUT_HDL_DIR/build/${TOPLEVEL}_VHarness.v hdl/${TOPLEVEL}_VHarness.v

# Generate Verilator TB interface
rfuzz_interface_gen.py \
  -o $HW/tb/cpp/include/rfuzz_tb_interface.h \
  -i $DUT_HDL_DIR/build/$TOPLEVEL.toml

# Create seed file with appropriate about of zero bytes (RFUZZ seeds 0)
NUM_ZERO_BYTES=$(grep "InputSize" $HW/tb/cpp/include/rfuzz_tb_interface.h |
  awk '{print $6}' | sed 's/;//')
dd if=/dev/zero of=$DUT/seeds/test.hwf count=1 bs=$((NUM_ZERO_BYTES * SEED_CYCLES))
xxd $DUT/seeds/test.hwf
exit 0
