#!/bin/bash -eu
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LINE_SEP="-------------------------------------------------------------------"

################################################################################
################################################################################
## Make directory to store simulation output
################################################################################
################################################################################
if [ ! -d "out" ]; then
  mkdir -p out
fi

################################################################################
################################################################################
## Install test bench dependencies
################################################################################
################################################################################
echo $LINE_SEP
echo "Installing dependencies for testbench ..."
if [[ ! -f tb/$TB_TYPE/$TB/requirements.txt ]]; then
  echo "No dependencies to install."
else
  python3 -m pip install -r tb/$TB_TYPE/$TB/requirements.txt
  check-exit-code
fi
echo "Done!"

################################################################################
################################################################################
## Build and execute the SW model of the circuit
################################################################################
################################################################################
echo $LINE_SEP
echo "Verilating/Compiling/Instrumenting/Simulating the DUT ..."
make clean
make \
  TB_TYPE=$TB_TYPE \
  TB=$TB \
  DISABLE_VCD_TRACING=1 \
  sim
check-exit-code

################################################################################
################################################################################
## Copy simulation results to out directory
################################################################################
################################################################################
cp results.xml out/
find out -type f -exec chmod 644 {} \;

################################################################################
################################################################################
## Done
################################################################################
################################################################################
echo -e "\e[1;32mSIMULATION SUCCESSFUL -- Done!\e[0m"
exit 0
