#!/bin/bash
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LINE_SEP="-------------------------------------------------------------------"

################################################################################
################################################################################
## Re-build simulation EXE with VCD tracing enabled
################################################################################
################################################################################
echo "Re-building HW model with VCD tracing enabled ..."

# Move to target CORE dir
cd $SRC/circuits/$CORE

# Verilate hardware
echo "Verilating hardware ..."
MODEL_DIR=$SRC/circuits/$CORE/$EXP_DATA_PATH/model_${FUZZER_INSTANCE_BASENAME}_vcd
MODEL_DIR=$MODEL_DIR make verilate
echo "Done!"
echo $LINE_SEP

# Set compilers
echo "Setting compiler/linker flags ..."
export CC="clang"
export CXX="clang++"
export CCC="clang++"
export VLT_CXX="clang++"
export CFLAGS=""
export CXXFLAGS=""
export VLT_CXXFLAGS=""
export LDFLAGS=""

# Print compiler/linker flags
echo "Compiler/Linker Flags:"
echo "CC=$CC"
echo "CXX=$CXX"
echo "CFLAGS=$CFLAGS"
echo "CXXFLAGS=$CXXFLAGS"
echo "VLT_CXXFLAGS=$VLT_CXXFLAGS"
echo "LDFLAGS=$LDFLAGS"
echo "Done!"
echo $LINE_SEP

# Make a build directory to store AFLGo compiler inputs/outputs
BUILD_DIR=$SRC/circuits/$CORE/$EXP_DATA_PATH/build_${FUZZER_INSTANCE_BASENAME}_vcd
mkdir -p $BUILD_DIR

# Make a bin directory to store instrumented EXEs
BIN_DIR=$SRC/circuits/$CORE/$EXP_DATA_PATH/bin_${FUZZER_INSTANCE_BASENAME}_vcd
mkdir -p $BIN_DIR

# Compile SW model of HW
echo "Compiling SW model of HW ..."
MODEL_DIR=$MODEL_DIR BUILD_DIR=$BUILD_DIR BIN_DIR=$BIN_DIR make exe

echo "Done!"
echo $LINE_SEP

################################################################################
################################################################################
## Generate VCD traces
################################################################################
################################################################################
echo "Generating VCD traces of fuzzer generated seeds ..."
echo $LINE_SEP

# iterate over test files generated by AFLGO
cd $EXP_DATA_PATH/$FUZZER_OUTPUT_DIR
for (( num=1; num <= $NUM_INSTANCES; num++ )); do
    echo "Generating VCD traces for fuzzer instance $num ..."
    cd ${FUZZER_INSTANCE_BASENAME}_${num} && mkdir -p vcd && cd vcd
    for test_file in "../queue/"*; do
        echo "|--Generating VCD trace for: $test_file ..."
        $BIN_DIR/V$CORE $test_file > /dev/null
    done
    cd .. && cd ..
done
echo "Done!"
echo $LINE_SEP

################################################################################
################################################################################
## Clean up build
################################################################################
################################################################################
echo "Cleaning up ..."
rm -rf $BUILD_DIR $BIN_DIR $MODEL_DIR
echo -e "\e[1;32mVCD TRACING SUCCESSFUL -- Done!\e[0m"
exit 0
