#!/bin/bash -eu
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LINE_SEP="-------------------------------------------------------------------"

################################################################################
################################################################################
## Set build flags
################################################################################
################################################################################
echo "Setting compiler/linker flags..."

# Set fuzzer compiler
CXX="$SRC/AFL/afl-clang-fast++"
CXXFLAGS=""

# Set Verilator compiler
VLT_CXX="clang++"
VLT_CXXFLAGS=""

# Print Fuzzer/Compiler/Linker Configurations
echo $LINE_SEP
make clean
make \
  CXX=$CXX \
  VLT_CXX=$VLT_CXX \
  CXXFLAGS=$CXXFLAGS \
  VLT_CXXFLAGS=$VLT_CXXFLAGS \
  OPT_SLOW=$OPT_SLOW \
  OPT_FAST=$OPT_FAST \
  OPT_GLOBAL=$OPT_GLOBAL \
  TB_TYPE=$TB_TYPE \
  TB=$TB \
  DISABLE_VCD_TRACING=1 \
  debug-make
echo "Done!"

################################################################################
################################################################################
## Install test bench dependencies
################################################################################
################################################################################
echo $LINE_SEP
echo "Installing dependencies for testbench ..."
if [[ ! -f tb/$TB_TYPE/$TB/packages.txt ]]; then
  echo "No dependencies to install."
else
  cat tb/$TB_TYPE/$TB/packages.txt | xargs apt-get install -y
  check-exit-code
fi
echo "Done!"

################################################################################
################################################################################
## Verilate HDL and Compile/Instrument SW Model
################################################################################
################################################################################
echo $LINE_SEP
echo "Verilating/Compiling/Instrumenting the DUT ..."
make \
  CXX=$CXX \
  VLT_CXX=$VLT_CXX \
  CXXFLAGS=$CXXFLAGS \
  VLT_CXXFLAGS=$VLT_CXXFLAGS \
  OPT_SLOW=$OPT_SLOW \
  OPT_FAST=$OPT_FAST \
  OPT_GLOBAL=$OPT_GLOBAL \
  TB_TYPE=$TB_TYPE \
  TB=$TB \
  DISABLE_VCD_TRACING=1
check-exit-code
echo "Done!"

################################################################################
################################################################################
## Done
################################################################################
################################################################################
echo $LINE_SEP
echo -e "\e[1;32mBUILD & INSTRUMENTATION SUCCESSFUL -- Done!\e[0m"
exit 0
