#!/bin/bash
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function check_exit_code {
    if [[ "$?" != "0" ]]; then
        exit 1
    fi
}

if [ ! -d "logs" ]; then
    mkdir -p logs
fi

# Generate HDL
generate_hdl 2>&1 | tee logs/exp.log
check_exit_code

if [[ $FUZZER == "cocotb" ]]; then
  # Simulate the DUT with cocotb
  verilate_and_sim 2>&1 | tee -a logs/exp.log
  check_exit_code
else
  # Compile the DUT for fuzzing
  compile 2>&1 | tee -a logs/exp.log
  check_exit_code

  # Fuzz the DUT
  fuzz 2>&1 | tee -a logs/exp.log
  check_exit_code
fi

# If on GCP --> save data and tear down VM
save_and_shutdown
exit 0
